services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: petradar-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"

  redis:
    image: redis:alpine
    container_name: petradar-redis
    ports:
      - "6379:6379"

  api:
    image: ghcr.io/jairo0624/petradar-api:latest
    container_name: petradar-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres 
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - MAILER_EMAIL=${MAILER_EMAIL}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SERVICE=${MAILER_SERVICE}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}

    depends_on:
      - postgres
      - redis